--
-- PostgreSQL database dump
--

\restrict Wr8naz8v5sjYFFmZIr1wHNbkfpnKtSZ4dYiqe9TfhrZcnLlckcEWmd9iKRrcW95

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_users (
    admin_level character varying(255),
    id bigint NOT NULL
);


--
-- Name: dishes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dishes (
    id bigint NOT NULL,
    balance integer NOT NULL,
    code character varying(10) NOT NULL,
    image_url character varying(512) NOT NULL,
    initial_stock integer NOT NULL,
    menu_date date NOT NULL,
    name character varying(255) NOT NULL,
    preparation_time integer NOT NULL,
    price numeric(10,2) NOT NULL,
    special_request_options character varying(500),
    status character varying(255),
    category character varying(20) DEFAULT 'NORMAL'::character varying,
    published boolean DEFAULT false NOT NULL,
    CONSTRAINT dishes_status_check CHECK (((status)::text = ANY ((ARRAY['ON_LIST'::character varying, 'SOLD_OUT'::character varying])::text[])))
);


--
-- Name: dishes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dishes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dishes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: drinks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drinks (
    id bigint NOT NULL,
    balance integer NOT NULL,
    code character varying(10) NOT NULL,
    image_url character varying(512) NOT NULL,
    name character varying(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    special_request_options character varying(500),
    status character varying(20) NOT NULL,
    CONSTRAINT drinks_status_check CHECK (((status)::text = ANY ((ARRAY['ON_LIST'::character varying, 'SOLD_OUT'::character varying])::text[])))
);


--
-- Name: drinks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.drinks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drinks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedbacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedbacks (
    id bigint NOT NULL,
    content character varying(1000) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    phone character varying(255),
    user_id bigint
);


--
-- Name: feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kitchen_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kitchen_users (
    vendor_name character varying(255),
    id bigint NOT NULL
);


--
-- Name: meal_pickups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meal_pickups (
    pickup_id bigint NOT NULL,
    actual_time timestamp(6) with time zone,
    admin_id bigint,
    admin_notified boolean NOT NULL,
    expected_time timestamp(6) with time zone,
    item_id bigint NOT NULL,
    method character varying(10)
);


--
-- Name: meal_pickups_pickup_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meal_pickups ALTER COLUMN pickup_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meal_pickups_pickup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_dishes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_dishes (
    menu_id bigint NOT NULL,
    dish_id bigint NOT NULL
);


--
-- Name: menu_drinks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_drinks (
    menu_id bigint NOT NULL,
    drink_id bigint NOT NULL
);


--
-- Name: menus; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menus (
    id bigint NOT NULL,
    balance integer NOT NULL,
    end_time time(6) without time zone NOT NULL,
    image_url character varying(512) NOT NULL,
    initial_stock integer NOT NULL,
    menu_date date NOT NULL,
    name character varying(255) NOT NULL,
    start_time time(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT menus_status_check CHECK (((status)::text = ANY ((ARRAY['ON_LIST'::character varying, 'SOLD_OUT'::character varying])::text[])))
);


--
-- Name: menus_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    item_id bigint NOT NULL,
    menu_id bigint,
    pickup_status character varying(255),
    quantity integer,
    special_note character varying(200),
    unit_price numeric(10,2),
    order_id bigint,
    menu_type character varying(10),
    CONSTRAINT order_items_pickup_status_check CHECK (((pickup_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PICKED_UP'::character varying])::text[])))
);


--
-- Name: order_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_window_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_window_config (
    id bigint NOT NULL,
    enforced boolean NOT NULL,
    slot1_end character varying(5) NOT NULL,
    slot1_start character varying(5) NOT NULL,
    slot2_end character varying(5),
    slot2_start character varying(5),
    zone_id character varying(50) NOT NULL
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    order_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deposit_amt numeric(10,2),
    order_status character varying(255),
    total_amt numeric(15,2),
    total_qty integer,
    user_id bigint,
    phone character varying(20),
    CONSTRAINT orders_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['PENDING_PAY'::character varying, 'DEPOSIT_PAID'::character varying, 'FULLY_PAID'::character varying, 'COMPLETE'::character varying])::text[])))
);


--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stripe_topup_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stripe_topup_records (
    id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    stripe_payment_intent_id character varying(255),
    stripe_session_id character varying(255) NOT NULL,
    wallet_id bigint NOT NULL,
    CONSTRAINT stripe_topup_records_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: stripe_topup_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stripe_topup_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stripe_topup_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    student_id character varying(255),
    id bigint NOT NULL
);


--
-- Name: teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teachers (
    employee_id character varying(255),
    id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password_hash character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet_transactions (
    transaction_id bigint NOT NULL,
    admin_id bigint,
    amount numeric(15,2),
    created_at timestamp(6) without time zone,
    description character varying(255),
    idempotency_key character varying(255),
    type character varying(255),
    wallet_id bigint,
    CONSTRAINT wallet_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['RECHARGE'::character varying, 'DEDUCT'::character varying, 'REFUND'::character varying, 'STRIPE_TOPUP'::character varying])::text[])))
);


--
-- Name: wallet_transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet_transactions ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_transactions_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallets (
    wallet_id bigint NOT NULL,
    balance numeric(15,2),
    user_id bigint
);


--
-- Name: wallets_wallet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallets ALTER COLUMN wallet_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallets_wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: admin_users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.admin_users (admin_level, id) FROM stdin;
\.


--
-- Data for Name: dishes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.dishes (id, balance, code, image_url, initial_stock, menu_date, name, preparation_time, price, special_request_options, status, category, published) FROM stdin;
9	50	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1781077498175-3329.jpg	50	2026-06-10	豉汁蒸排骨飯	10	60.00	no soy sauce, with soy sauce	ON_LIST	FRIDAY	t
3	45	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1780994201075-3687.jpg	30	2026-06-09	凱撒沙律	10	48.00	\N	ON_LIST	NORMAL	t
10	50	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1781077545798-7142.jpg	50	2026-06-10	玫瑰豉油雞	10	60.00	fried rice, white rice	ON_LIST	FRIDAY	t
2	50	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1780994193641-8171.jpg	50	2026-06-09	招牌咖哩牛腩飯	10	55.00	\N	ON_LIST	MONDAY	f
4	50	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1780994530671-1997.jpg	50	2026-06-09	豬扒飯	10	60.00	no cheese, fried rice, white rice	ON_LIST	MONDAY	f
5	50	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1781077219265-4559.jpg	50	2026-06-10	燒肉飯	10	60.00	fried rice, white rice	ON_LIST	WEDNESDAY	f
7	50	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1781077357843-3272.jpg	50	2026-06-10	蜜汁叉燒飯	10	60.00	fried rice, white rice	ON_LIST	WEDNESDAY	f
8	50	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1781077418553-3506.jpg	50	2026-06-10	宮保雞丁飯	10	60.00	fried rice, white rice	ON_LIST	THURSDAY	f
6	50	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1781077308608-1210.jpg	50	2026-06-10	滑蛋蝦仁飯	10	60.00	fried rice, white rice	ON_LIST	SATURDAY	f
1	3	DISH	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/dish_1780994178266-3631.jpg	50	2026-06-09	黯然銷魂飯	10	60.00	\N	ON_LIST	TUESDAY	f
\.


--
-- Data for Name: drinks; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.drinks (id, balance, code, image_url, name, price, special_request_options, status) FROM stdin;
4	50	DRINK	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/drink_1781077797791-6732.jpg	凍檸檬茶	25.00	less sugar, no sugar	ON_LIST
5	50	DRINK	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/drink_1781078364514-6737.jpg	凍咖啡	25.00	less sugar, no sugar, no milk, extra milk	ON_LIST
1	50	DRINK	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/drink_1780994214695-1461.jpg	熱咖啡	15.00	less sugar, no sugar, no milk, extra milk	ON_LIST
2	50	DRINK	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/drink_1780994562788-3466.jpg	熱奶茶	20.00	less sugar, no sugar	ON_LIST
3	50	DRINK	https://pub-e47315ff76f145eeae9e5a2f8486bea8.r2.dev/drink_1781077708059-4180.jpg	凍鹹檸七	20.00	less sugar	ON_LIST
\.


--
-- Data for Name: feedbacks; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.feedbacks (id, content, created_at, is_read, phone, user_id) FROM stdin;
\.


--
-- Data for Name: kitchen_users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.kitchen_users (vendor_name, id) FROM stdin;
\.


--
-- Data for Name: meal_pickups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.meal_pickups (pickup_id, actual_time, admin_id, admin_notified, expected_time, item_id, method) FROM stdin;
1	\N	\N	f	2026-06-10 05:22:49.142222+00	4	0001-003
2	\N	\N	f	2026-06-10 05:22:49.142222+00	5	0001-003
3	\N	\N	f	2026-06-10 05:23:02.56251+00	6	0001-004
4	\N	\N	f	2026-06-10 05:23:02.56251+00	7	0001-004
5	\N	\N	f	2026-06-10 05:26:59.727801+00	8	0001-005
6	\N	\N	f	2026-06-10 05:26:59.727801+00	9	0001-005
7	\N	\N	f	2026-06-10 05:28:09.710507+00	10	0001-006
8	\N	\N	f	2026-06-10 05:28:09.710507+00	11	0001-006
9	\N	\N	f	2026-06-10 07:11:40.093773+00	12	0001-007
10	\N	\N	f	2026-06-10 07:11:40.093773+00	13	0001-007
11	\N	\N	f	2026-06-10 07:13:03.020246+00	14	0001-008
12	\N	\N	f	2026-06-10 07:13:03.020246+00	15	0001-008
13	\N	\N	f	2026-06-10 07:34:22.532239+00	16	0001-009
14	\N	\N	f	2026-06-10 07:34:22.532239+00	17	0001-009
15	\N	\N	f	2026-06-10 07:34:43.981436+00	18	0001-010
16	\N	\N	f	2026-06-10 07:34:43.981436+00	19	0001-010
17	\N	\N	f	2026-06-10 08:00:30.847449+00	20	0001-011
18	\N	\N	f	2026-06-10 08:00:30.847449+00	21	0001-011
19	\N	\N	f	2026-06-10 08:02:04.461426+00	22	0003-012
20	\N	\N	f	2026-06-10 08:02:04.461426+00	23	0003-012
21	\N	\N	f	2026-06-10 08:07:59.11344+00	24	0001-013
22	\N	\N	f	2026-06-10 08:07:59.11344+00	25	0001-013
23	\N	\N	f	2026-06-10 08:57:46.115136+00	26	0002-014
24	\N	\N	f	2026-06-10 08:57:46.115136+00	27	0002-014
25	\N	\N	f	2026-06-10 17:45:43.58515+00	28	0001-015
26	\N	\N	f	2026-06-10 17:45:43.58515+00	29	0001-015
27	\N	\N	f	2026-06-10 17:59:22.317272+00	30	0001-016
28	\N	\N	f	2026-06-10 17:59:22.317272+00	31	0001-016
29	\N	\N	f	2026-06-10 18:03:45.728801+00	32	0001-017
30	\N	\N	f	2026-06-10 18:03:45.728801+00	33	0001-017
31	\N	\N	f	2026-06-10 18:19:19.026847+00	34	0289-018
32	\N	\N	f	2026-06-10 18:19:19.026847+00	35	0289-018
33	\N	\N	f	2026-06-11 05:55:43.647893+00	36	6789-019
34	\N	\N	f	2026-06-11 06:23:57.485327+00	37	4321-020
35	\N	\N	f	2026-06-11 06:23:57.485327+00	38	4321-020
36	\N	\N	f	2026-06-11 06:23:57.485327+00	39	4321-020
37	\N	\N	f	2026-06-11 06:25:41.035345+00	40	1234-021
38	\N	\N	f	2026-06-11 09:52:18.619474+00	41	0289-022
39	\N	\N	f	2026-06-11 09:52:18.619474+00	42	0289-022
\.


--
-- Data for Name: menu_dishes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.menu_dishes (menu_id, dish_id) FROM stdin;
\.


--
-- Data for Name: menu_drinks; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.menu_drinks (menu_id, drink_id) FROM stdin;
\.


--
-- Data for Name: menus; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.menus (id, balance, end_time, image_url, initial_stock, menu_date, name, start_time, status) FROM stdin;
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_items (item_id, menu_id, pickup_status, quantity, special_note, unit_price, order_id, menu_type) FROM stdin;
1	2	PENDING	1		60.00	1	\N
2	102	PENDING	1		0.00	1	\N
3	1	PENDING	1	No Onion, Extra Sauce	48.00	2	\N
4	4	PENDING	1		60.00	3	\N
5	1	PENDING	1		0.00	3	\N
6	4	PENDING	1		60.00	4	\N
7	1	PENDING	1		0.00	4	\N
8	4	PENDING	1		60.00	5	\N
9	1	PENDING	1		0.00	5	\N
10	4	PENDING	1		60.00	6	\N
11	1	PENDING	1		0.00	6	\N
12	1	PENDING	1		60.00	7	\N
13	1	PENDING	1		0.00	7	\N
14	1	PENDING	1		60.00	8	\N
15	1	PENDING	1		0.00	8	\N
16	1	PENDING	1		60.00	9	DISH
17	1	PENDING	1		0.00	9	DRINK
18	1	PENDING	1		60.00	10	DISH
19	1	PENDING	1		0.00	10	DRINK
20	4	PENDING	1	fried rice	60.00	11	DISH
21	1	PENDING	1		0.00	11	DRINK
22	1	PENDING	1		60.00	12	DISH
23	2	PENDING	1		0.00	12	DRINK
24	1	PENDING	3		60.00	13	DISH
25	1	PENDING	3		0.00	13	DRINK
26	6	PENDING	1	white rice	60.00	14	DISH
27	2	PENDING	1	less sugar	0.00	14	DRINK
28	6	PENDING	1		60.00	15	DISH
29	4	PENDING	1		0.00	15	DRINK
30	6	PENDING	1		60.00	16	DISH
31	4	PENDING	1		0.00	16	DRINK
32	9	PENDING	1		60.00	17	DISH
33	5	PENDING	1		0.00	17	DRINK
34	6	PENDING	1		60.00	18	DISH
35	5	PENDING	1		0.00	18	DRINK
36	3	PENDING	1		48.00	19	DISH
37	1	PENDING	3		60.00	20	DISH
38	3	PENDING	3		48.00	20	DISH
39	2	PENDING	1		0.00	20	DRINK
40	1	PENDING	1		60.00	21	DISH
41	6	PENDING	1		60.00	22	DISH
42	4	PENDING	1		0.00	22	DRINK
\.


--
-- Data for Name: order_window_config; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_window_config (id, enforced, slot1_end, slot1_start, slot2_end, slot2_start, zone_id) FROM stdin;
1	t	18:00	00:00	23:59	18:00	Asia/Hong_Kong
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.orders (order_id, created_at, deposit_amt, order_status, total_amt, total_qty, user_id, phone) FROM stdin;
1	2026-06-08 17:40:06.159648	0.00	PENDING_PAY	60.00	2	1	\N
2	2026-06-09 08:50:40.855094	0.00	COMPLETE	48.00	1	2	\N
6	2026-06-10 04:58:09.400227	0.00	COMPLETE	60.00	2	1	\N
5	2026-06-10 04:56:59.696051	0.00	COMPLETE	60.00	2	1	\N
4	2026-06-10 04:53:02.529814	0.00	COMPLETE	60.00	2	1	\N
3	2026-06-10 04:52:49.059623	0.00	COMPLETE	60.00	2	1	\N
12	2026-06-10 07:32:04.432235	0.00	COMPLETE	60.00	2	3	12345679
13	2026-06-10 07:37:59.086607	50.00	COMPLETE	180.00	6	1	66820289
11	2026-06-10 07:30:30.693048	0.00	COMPLETE	60.00	2	1	66820289
10	2026-06-10 07:04:43.943415	0.00	COMPLETE	60.00	2	1	66820289
9	2026-06-10 07:04:22.376236	0.00	COMPLETE	60.00	2	1	66820289
8	2026-06-10 06:43:02.988434	0.00	COMPLETE	60.00	2	1	\N
7	2026-06-10 06:41:39.932619	0.00	COMPLETE	60.00	2	1	\N
14	2026-06-10 08:27:46.031006	0.00	COMPLETE	60.00	2	2	12345678
15	2026-06-10 17:15:43.427419	0.00	COMPLETE	60.00	2	1	66820289
16	2026-06-10 17:29:22.190717	0.00	COMPLETE	60.00	2	1	66820289
17	2026-06-10 17:33:45.697256	0.00	COMPLETE	60.00	2	1	66820289
18	2026-06-10 17:49:18.884405	0.00	COMPLETE	60.00	2	1	66820289
19	2026-06-11 05:25:43.605179	0.00	FULLY_PAID	48.00	1	6	23456789
20	2026-06-11 05:53:57.452048	50.00	DEPOSIT_PAID	324.00	7	9	87654321
21	2026-06-11 05:55:41.013204	0.00	FULLY_PAID	60.00	1	11	24681234
22	2026-06-11 09:22:18.425859	0.00	FULLY_PAID	60.00	2	1	66820289
\.


--
-- Data for Name: stripe_topup_records; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.stripe_topup_records (id, amount, created_at, status, stripe_payment_intent_id, stripe_session_id, wallet_id) FROM stdin;
1	500.00	2026-06-10 04:43:32.055264	SUCCEEDED	pi_3Tge1437uWYNwtpg1YfTKBUd	cs_test_a19hCJZL60moi7urI5IVjJmDDJtez540UM4WRd7RXie8eK8A4gYiAKQK7a	1
2	100.00	2026-06-10 07:34:59.780294	PENDING	\N	cs_test_a1cdcX6TFZQUVDgHNlk3w9HZpSE0xggDCOR96CFFLqmmyu80MjEkmHh4mw	3
3	100.00	2026-06-10 07:35:01.631015	PENDING	\N	cs_test_a1cObrgxrkcCj1o7yLw8gU2sLmRqGXM52AKgWaB4sxUMF89W3n9WoZgb19	3
4	100.00	2026-06-10 07:35:02.668561	PENDING	\N	cs_test_a1pxUr4vsWBS1x87Xba3iB1O7i12xbuLnGbaxZKf7yX1UWxJCpdhCg7c7A	3
5	100.00	2026-06-10 08:24:54.298916	SUCCEEDED	pi_3TghTm37uWYNwtpg1KSD23pH	cs_test_a1wHPMqGipi6H6XvPENNIJO2xrvx0v1AqJU9eFBOPJUmvrcYN0cNue0dxc	2
6	100.00	2026-06-11 05:23:49.578446	SUCCEEDED	pi_3Th16Z37uWYNwtpg0KaXMHvZ	cs_test_a1XUuDWyDj9pWbK2COxCYo8fG2NXPRb1wZRLNM9zujUutuIR8NjSOiirEP	4
7	5000.00	2026-06-11 05:50:54.037767	PENDING	\N	cs_test_a1w31Lu9tTJ4wd4rURVhcvMnGFO9F36wguxu4BrblvNoSVriQTmoWXY9mJ	5
8	5000.00	2026-06-11 05:51:23.650595	SUCCEEDED	pi_3Th1XU37uWYNwtpg0iC1mGVB	cs_test_a1R5x1kF536tpjdCkraITy2a2ilFEwJTEg7Aud83GDfjLV9I4XDdXvnhpJ	5
9	500.00	2026-06-11 05:53:27.307957	SUCCEEDED	pi_3Th1a737uWYNwtpg1vhjJM9E	cs_test_a10j93RBAUzsAPh738beCultbv45pbDuWbj7W0oTMwsMLPg8VdxXv44dWt	6
10	200.00	2026-06-11 06:28:52.806806	PENDING	\N	cs_test_a1h4nlZ64UYkjCMYeg5coz0pByKTo2AxEYSXsEbm6vajP64SNQ8CQcvkST	7
\.


--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.students (student_id, id) FROM stdin;
s11111111	1
s12345678	2
s98769999	6
s13579246	11
s44332211	15
\.


--
-- Data for Name: teachers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.teachers (employee_id, id) FROM stdin;
t12345679	3
t87654321	9
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, password_hash, phone, role) FROM stdin;
1	$2a$10$2nI6M2Kz42tJ3IhMpD/nd.fbdFirL/PMLWfSqHulIqH6bayiXZYIS	66820289	STUDENT
2	$2a$10$w40L9Ra8wovv57dDhcAfFutpOfFqgHCTKIQcQqEDN/ykEmQBBTUki	12345678	STUDENT
3	$2a$10$ziZWWRlTkC4aMortbqlctOn3Vq/LI/lzed2zslus160zwmX0ZyEhK	12345679	TEACHER
6	$2a$10$4qRvdSl.ZWL5ZuL8ijHD2e4KpCDXs2/F/i/CL3oyMVkvbNNXUt8ay	23456789	STUDENT
9	$2a$10$HlRvpx8xwRDT7peymfZjbeg5JAQK7.jlkcm9WhZiK3MEin21aw3/G	87654321	TEACHER
11	$2a$10$gmGGS5f.4No.oy5ZdRnNjOBSyuJidfDAA947GPgaiudgKw88s5vPu	24681234	STUDENT
15	$2a$10$so/mDzCpVWEP/bQv9cgJBuZn2JUhuIFBGKgzfwikU5595FWwJgJGy	88882222	STUDENT
\.


--
-- Data for Name: wallet_transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.wallet_transactions (transaction_id, admin_id, amount, created_at, description, idempotency_key, type, wallet_id) FROM stdin;
1	\N	500.00	2026-06-10 04:52:23.89202	Stripe top-up via session cs_test_a19hCJZL60moi7urI5IVjJmDDJtez540UM4WRd7RXie8eK8A4gYiAKQK7a	stripe-cs_test_a19hCJZL60moi7urI5IVjJmDDJtez540UM4WRd7RXie8eK8A4gYiAKQK7a	STRIPE_TOPUP	1
2	\N	60.00	2026-06-10 04:52:49.111609	Order payment	order-3-pay	DEDUCT	1
4	\N	60.00	2026-06-10 04:53:02.54986	Order payment	order-4-pay	DEDUCT	1
6	\N	60.00	2026-06-10 04:56:59.718074	Order payment	order-5-pay	DEDUCT	1
8	\N	60.00	2026-06-10 04:58:09.661834	Order payment	order-6-pay	DEDUCT	1
9	1	500.00	2026-06-10 06:37:26.722173	現金儲值	admin-recharge-1-1781073447031	RECHARGE	1
10	\N	60.00	2026-06-10 06:41:40.069915	Order payment	order-7-pay	DEDUCT	1
11	\N	60.00	2026-06-10 06:43:03.009677	Order payment	order-8-pay	DEDUCT	1
12	\N	60.00	2026-06-10 07:04:22.500953	Order payment	order-9-pay	DEDUCT	1
13	\N	60.00	2026-06-10 07:04:43.968464	Order payment	order-10-pay	DEDUCT	1
14	\N	60.00	2026-06-10 07:30:30.811188	Order payment	order-11-pay	DEDUCT	1
15	1	100.00	2026-06-10 07:31:22.575938	現金儲值	admin-recharge-1-1781076683002	RECHARGE	1
16	1	100.00	2026-06-10 07:31:32.826236	現金儲值	admin-recharge-3-1781076693254	RECHARGE	3
17	\N	60.00	2026-06-10 07:32:04.451984	Order payment	order-12-pay	DEDUCT	3
18	\N	50.00	2026-06-10 07:37:59.10546	Order payment	order-13-pay	DEDUCT	1
19	\N	100.00	2026-06-10 08:27:22.905021	Stripe top-up via session cs_test_a1wHPMqGipi6H6XvPENNIJO2xrvx0v1AqJU9eFBOPJUmvrcYN0cNue0dxc	stripe-cs_test_a1wHPMqGipi6H6XvPENNIJO2xrvx0v1AqJU9eFBOPJUmvrcYN0cNue0dxc	STRIPE_TOPUP	2
20	\N	60.00	2026-06-10 08:27:46.093536	Order payment	order-14-pay	DEDUCT	2
21	\N	60.00	2026-06-10 17:15:43.560367	Order payment	order-15-pay	DEDUCT	1
22	\N	60.00	2026-06-10 17:29:22.283216	Order payment	order-16-pay	DEDUCT	1
23	\N	60.00	2026-06-10 17:33:45.719054	Order payment	order-17-pay	DEDUCT	1
24	\N	60.00	2026-06-10 17:49:18.995428	Order payment	order-18-pay	DEDUCT	1
25	\N	100.00	2026-06-11 05:24:42.833947	Stripe top-up via session cs_test_a1XUuDWyDj9pWbK2COxCYo8fG2NXPRb1wZRLNM9zujUutuIR8NjSOiirEP	stripe-cs_test_a1XUuDWyDj9pWbK2COxCYo8fG2NXPRb1wZRLNM9zujUutuIR8NjSOiirEP	STRIPE_TOPUP	4
26	\N	48.00	2026-06-11 05:25:43.635709	Order payment	order-19-pay	DEDUCT	4
27	\N	5000.00	2026-06-11 05:52:32.546355	Stripe top-up via session cs_test_a1R5x1kF536tpjdCkraITy2a2ilFEwJTEg7Aud83GDfjLV9I4XDdXvnhpJ	stripe-cs_test_a1R5x1kF536tpjdCkraITy2a2ilFEwJTEg7Aud83GDfjLV9I4XDdXvnhpJ	STRIPE_TOPUP	5
28	\N	50.00	2026-06-11 05:53:57.47667	Order payment	order-20-pay	DEDUCT	5
29	\N	500.00	2026-06-11 05:55:16.661605	Stripe top-up via session cs_test_a10j93RBAUzsAPh738beCultbv45pbDuWbj7W0oTMwsMLPg8VdxXv44dWt	stripe-cs_test_a10j93RBAUzsAPh738beCultbv45pbDuWbj7W0oTMwsMLPg8VdxXv44dWt	STRIPE_TOPUP	6
30	\N	60.00	2026-06-11 05:55:41.027794	Order payment	order-21-pay	DEDUCT	6
31	\N	60.00	2026-06-11 09:22:18.580279	Order payment	order-22-pay	DEDUCT	1
\.


--
-- Data for Name: wallets; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.wallets (wallet_id, balance, user_id) FROM stdin;
3	40.00	3
2	40.00	2
4	52.00	6
5	4950.00	9
6	440.00	11
7	0.00	15
1	210.00	1
\.


--
-- Name: dishes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.dishes_id_seq', 10, true);


--
-- Name: drinks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.drinks_id_seq', 5, true);


--
-- Name: feedbacks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.feedbacks_id_seq', 1, false);


--
-- Name: meal_pickups_pickup_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.meal_pickups_pickup_id_seq', 39, true);


--
-- Name: menus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.menus_id_seq', 1, false);


--
-- Name: order_items_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_items_item_id_seq', 42, true);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 22, true);


--
-- Name: stripe_topup_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.stripe_topup_records_id_seq', 10, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 15, true);


--
-- Name: wallet_transactions_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.wallet_transactions_transaction_id_seq', 31, true);


--
-- Name: wallets_wallet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.wallets_wallet_id_seq', 7, true);


--
-- Name: admin_users admin_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT admin_users_pkey PRIMARY KEY (id);


--
-- Name: dishes dishes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dishes
    ADD CONSTRAINT dishes_pkey PRIMARY KEY (id);


--
-- Name: drinks drinks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drinks
    ADD CONSTRAINT drinks_pkey PRIMARY KEY (id);


--
-- Name: feedbacks feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT feedbacks_pkey PRIMARY KEY (id);


--
-- Name: kitchen_users kitchen_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kitchen_users
    ADD CONSTRAINT kitchen_users_pkey PRIMARY KEY (id);


--
-- Name: meal_pickups meal_pickups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meal_pickups
    ADD CONSTRAINT meal_pickups_pkey PRIMARY KEY (pickup_id);


--
-- Name: menu_dishes menu_dishes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_dishes
    ADD CONSTRAINT menu_dishes_pkey PRIMARY KEY (menu_id, dish_id);


--
-- Name: menu_drinks menu_drinks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_drinks
    ADD CONSTRAINT menu_drinks_pkey PRIMARY KEY (menu_id, drink_id);


--
-- Name: menus menus_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menus
    ADD CONSTRAINT menus_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (item_id);


--
-- Name: order_window_config order_window_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_window_config
    ADD CONSTRAINT order_window_config_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


--
-- Name: stripe_topup_records stripe_topup_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stripe_topup_records
    ADD CONSTRAINT stripe_topup_records_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: stripe_topup_records uk2ppiveuekbnwdl3u3jrusqqh1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stripe_topup_records
    ADD CONSTRAINT uk2ppiveuekbnwdl3u3jrusqqh1 UNIQUE (stripe_session_id);


--
-- Name: admin_users uk4alfl0h6b2lnrhbr1et3u3s3b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT uk4alfl0h6b2lnrhbr1et3u3s3b UNIQUE (admin_level);


--
-- Name: students uk5mbus2m1tm2acucrp6t627jmx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uk5mbus2m1tm2acucrp6t627jmx UNIQUE (student_id);


--
-- Name: teachers uk8xdh0jsitskwq83arwxvyihhc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT uk8xdh0jsitskwq83arwxvyihhc UNIQUE (employee_id);


--
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);


--
-- Name: wallet_transactions ukfdj7qah64spdb3ap7ioeqatv7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT ukfdj7qah64spdb3ap7ioeqatv7 UNIQUE (idempotency_key);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wallet_transactions wallet_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT wallet_transactions_pkey PRIMARY KEY (transaction_id);


--
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (wallet_id);


--
-- Name: menu_drinks fk46bp9j34maqg4wmu7fmv0ccst; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_drinks
    ADD CONSTRAINT fk46bp9j34maqg4wmu7fmv0ccst FOREIGN KEY (menu_id) REFERENCES public.menus(id);


--
-- Name: students fk7xqmtv7r2eb5axni3jm0a80su; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fk7xqmtv7r2eb5axni3jm0a80su FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: wallet_transactions fk8seu7b87ifqi09ghhssusmb0x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT fk8seu7b87ifqi09ghhssusmb0x FOREIGN KEY (wallet_id) REFERENCES public.wallets(wallet_id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(order_id);


--
-- Name: menu_drinks fkbwi8i3gfag388a0j87mh34ent; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_drinks
    ADD CONSTRAINT fkbwi8i3gfag388a0j87mh34ent FOREIGN KEY (drink_id) REFERENCES public.drinks(id);


--
-- Name: menu_dishes fkju5e0tckotyelvotf79x2g86a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_dishes
    ADD CONSTRAINT fkju5e0tckotyelvotf79x2g86a FOREIGN KEY (dish_id) REFERENCES public.dishes(id);


--
-- Name: admin_users fkkwx01p5bol0oql5llbr6morkt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT fkkwx01p5bol0oql5llbr6morkt FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: teachers fkpavufmal5lbtc60csriy8sx3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT fkpavufmal5lbtc60csriy8sx3 FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: kitchen_users fkq893vi5tar0ji9vj57ltugema; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kitchen_users
    ADD CONSTRAINT fkq893vi5tar0ji9vj57ltugema FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: menu_dishes fkswx1syrr3knmdl1tn5dksx3tv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_dishes
    ADD CONSTRAINT fkswx1syrr3knmdl1tn5dksx3tv FOREIGN KEY (menu_id) REFERENCES public.menus(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Wr8naz8v5sjYFFmZIr1wHNbkfpnKtSZ4dYiqe9TfhrZcnLlckcEWmd9iKRrcW95

