# Run: CREATE DATABASE restaurant_pos; in psql before starting
spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/restaurant_pos"
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
